//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resources.rc
//
#define IDC_LASTSEEDS                   3
#define IDC_DEFAULTS                    4
#define IDC_RANDOMISE                   5
#define IDC_APPLYALL                    6
#define IDB_CLOSEOFF                    101
#define IDB_CLOSEON                     102
#define IDB_CLOSEOVER                   103
#define IDB_MAXDISABLED                 104
#define IDB_MAXOFF                      105
#define IDB_MAXON                       106
#define IDB_MAXOVER                     107
#define IDB_MINOFF                      108
#define IDB_MINON                       109
#define IDB_MINOVER                     110
#define IDB_RESTOREOFF                  111
#define IDB_RESTOREON                   112
#define IDB_RESTOREOVER                 113
#define IDB_TITLEBAR                    114
#define IDB_TOOTLIPLEFT                 115
#define IDB_TOOLTIPLEFT                 115
#define IDB_TOOLTIPRIGHT                116
#define IDB_TOOLTIP                     117
#define IDB_STARFIELDBACK               118
#define IDB_NEWOFF                      119
#define IDB_NEWON                       120
#define IDB_NEWOVER                     121
#define IDB_EXITOVER                    122
#define IDB_EXITON                      123
#define IDB_EXITOFF                     124
#define IDB_BACKGROUNDOFF               125
#define IDB_BACKGROUNDON                126
#define IDB_BACKGROUNDOVER              127
#define IDB_STARFIELDOVER               131
#define IDB_STARFIELDON                 132
#define IDB_STARFIELDOFF                133
#define IDB_RANDOMOVER                  134
#define IDB_RANDOMON                    135
#define IDB_RANDOMOFF                   136
#define IDB_SOLIDCOLOUROVER             138
#define IDB_SOLIDCOLOURON               139
#define IDB_SOLIDCOLOUROFF              140
#define IDI_MULTISOFT                   141
#define IDB_UNDOREDOOVER                143
#define IDB_UNDOREDOON                  144
#define IDB_UNDOREDOOFF                 145
#define IDB_BUFFERSWAPOVER              146
#define IDB_BUFFERLOADON                147
#define IDB_BUFFERLOADOVER              148
#define IDB_BUFFERSAVEOFF               149
#define IDB_BUFFERSAVEON                150
#define IDB_BUFFERSAVEOVER              151
#define IDB_BUFFERSWAPOFF               152
#define IDB_BUFFERSWAPON                153
#define IDB_BUFFERLOADOFF               154
#define IDB_VIEWIMAGEOVER               156
#define IDB_VIEWIMAGEON                 157
#define IDB_VIEWIMAGEOFF                158
#define IDB_VIEWBUFFEROVER              159
#define IDB_VIEWBUFFERON                160
#define IDB_VIEWBUFFEROFF               161
#define IDB_NEBULAOVER                  162
#define IDB_NEBULAON                    163
#define IDB_NEBULAOFF                   164
#define IDB_SAVEOVER                    165
#define IDB_SAVEON                      166
#define IDB_SAVEOFF                     167
#define IDB_DRAWOVER                    168
#define IDB_DRAWON                      169
#define IDB_DRAWOFF                     170
#define IDD_NEBULA                      173
#define IDB_HIDEOVER                    174
#define IDB_BUFFERON                    175
#define IDB_BUFFEROVER                  176
#define IDB_HIDEOFF                     177
#define IDB_HIDEON                      178
#define IDB_BUFFEROFF                   179
#define IDB_ABORTOVER                   180
#define IDB_ABORTON                     181
#define IDB_ABORTOFF                    182
#define IDB_ABORTDISABLED               183
#define IDB_OPENOVER                    184
#define IDB_OPENON                      185
#define IDB_OPENOFF                     186
#define IDB_ADVANCEDOVER                187
#define IDB_ADVANCEDON                  188
#define IDB_ADVANCEDOFF                 189
#define IDB_UNDERLAYIMAGEON             190
#define IDB_UNDERLAYIMAGEOFF            193
#define IDB_UNDERLAYIMAGEOVER           195
#define IDD_NEW                         196
#define IDB_OVERLAYIMAGEON              198
#define IDB_OVERLAYIMAGEOFF             199
#define IDB_OVERLAYIMAGEOVER            200
#define IDB_MERGEIMAGESOVER             201
#define IDB_MERGEIMAGESON               202
#define IDB_MERGEIMAGESOFF              203
#define IDD_MERGE                       204
#define IDB_MISCFILTERSOVER             205
#define IDB_MISCFILTERSON               206
#define IDB_MISCFILTERSOFF              207
#define IDB_SMOOTHOVER                  208
#define IDB_SMOOTHON                    209
#define IDB_SMOOTHOFF                   210
#define IDB_STARON                      212
#define IDB_STAROFF                     213
#define IDB_STAROVER                    214
#define IDB_BASICSOVER                  215
#define IDB_BASICSON                    216
#define IDB_BASICSOFF                   217
#define IDB_SURFACEOFF                  218
#define IDB_FLARESON                    219
#define IDB_FLARESOVER                  220
#define IDB_FLARESOFF                   221
#define IDB_SURFACEON                   222
#define IDB_SURFACEOVER                 223
#define IDB_PLACESTAROVER               224
#define IDB_PLACESTARON                 225
#define IDB_PLACESTAROFF                226
#define IDB_CORONASIZEOVER              227
#define IDB_CORONASIZEON                228
#define IDB_CORONASIZEOFF               229
#define IDB_STARSIZEOFF                 231
#define IDB_STARSIZEON                  232
#define IDB_STARSIZEOVER                233
#define IDB_STARCOLOUROVER              240
#define IDB_STARCOLOURON                241
#define IDB_STARCOLOUROFF               242
#define IDB_UNLOCKOFF                   243
#define IDB_PLACESTARDISABLED           244
#define IDB_STARCOLOURDISABLED          245
#define IDB_UNLOCKDISABLED              246
#define IDB_CORONASIZEDISABLED          247
#define IDB_UNLOCKON                    248
#define IDB_UNLOCKOVER                  249
#define IDB_STARSIZEDISABLED            250
#define IDB_RANDOMDISABLED              251
#define IDB_DRAWDISABLED                252
#define IDB_ADVANCEDDISABLED            253
#define IDB_WINDOWBACKGROUND            255
#define IDB_BRUSHNOTHING                257
#define IDD_GRADIENT                    258
#define IDB_FINISHSTAROVER              259
#define IDB_CLEARSTAROFF                260
#define IDB_CLEARSTARON                 261
#define IDB_CLEARSTAROVER               262
#define IDB_FINISHSTARDISABLED          263
#define IDB_FINISHSTAROFF               264
#define IDB_FINISHSTARON                265
#define IDB_CLEARSTARDISABLED           266
#define IDB_EXPORTSTAROVER              267
#define IDB_EXPORTSTAROFF               268
#define IDB_EXPORTSTARON                269
#define IDB_EXPORTSTARDISABLED          270
#define IDB_HELPOVER                    272
#define IDB_HELPON                      273
#define IDB_HELPOFF                     274
#define IDB_GRADIENTOVER                275
#define IDB_GRADIENTON                  276
#define IDB_GRADIENTOFF                 277
#define IDB_HSCROLLTRACK                278
#define IDB_HSCROLLLARROWON             279
#define IDB_HSCROLLLARROWOVER           280
#define IDB_HSCROLLLARROWOFF            281
#define IDB_HSCROLLRARROWOVER           282
#define IDB_HSCROLLRARROWON             283
#define IDB_HSCROLLRARROWOFF            284
#define IDB_HSCROLLBAR                  285
#define IDB_HSCROLLBARLEFT              286
#define IDB_HSCROLLBARRIGHT             287
#define IDB_HSCROLLRARROWDISABLED       288
#define IDB_HSCROLLLARROWDISABLED       289
#define IDB_ANIMATIONOVER               290
#define IDB_ANIMATIONOFF                291
#define IDB_ANIMATIONON                 292
#define IDB_ANIMATIONDISABLED           293
#define IDD_NEBULAANIM                  294
#define IDB_GRADIENTDISABLED            295
#define IDC_SLDNUMBER                   1003
#define IDC_LBLNUMBER                   1004
#define IDC_LBLCURRENT                  1005
#define IDC_SLDCURRENT                  1006
#define IDC_LBLPREVIOUS                 1008
#define IDC_OPTPREVIOUSERASE            1009
#define IDC_OPTPREVIOUSUNDERLAY         1010
#define IDC_OPTPREVIOUSOVERLAY          1011
#define IDC_LBLSEED                     1012
#define IDC_TXTSEED                     1013
#define IDC_LBLPERSISTENCE              1014
#define IDC_LBLINTERPOLATION            1015
#define IDC_TXTPERSISTENCE              1016
#define IDC_LBLOCTAVES                  1017
#define IDC_TXTOCTAVES                  1018
#define IDC_LBLRED                      1019
#define IDC_TXTRED                      1020
#define IDC_LBLGREEN                    1021
#define IDC_TXTGREEN                    1022
#define IDC_COLOUR                      1023
#define IDC_CHKBUG                      1024
#define IDC_LBLBLUE                     1025
#define IDC_TXTBLUE                     1026
#define IDC_LBLFIRSTOCTAVE              1027
#define IDC_TXTFIRSTOCTAVE              1028
#define IDC_OPTINTERPOLATELINEAR        1029
#define IDC_OPTINTERPOLATECOSINE        1030
#define IDC_OPTINTERPOLATECUBIC         1031
#define IDC_CHKTILEH                    1032
#define IDC_CHKSMOOTH                   1033
#define IDC_CHKTILEV                    1034
#define IDC_FRACOMMONLAYERS             1035
#define IDC_CLOSE                       1036
#define IDC_DIMENSIONS                  1037
#define IDC_GRADIENT                    1037
#define IDC_LBLDIMENSIONS               1038
#define IDC_WIDTH                       1039
#define IDC_HEIGHT                      1040
#define IDC_LBLWIDTH                    1043
#define IDC_LBLHEIGHT                   1044
#define IDC_RESIZEBUFFER                1045
#define IDC_MERGEAMOUNT                 1046
#define IDC_MERGEPREVIEW                1047
#define IDC_LBLIMAGE                    1048
#define IDC_LBLBUFFER                   1049
#define IDC_GENERATE                    1050
#define IDC_GRADIENTDISPLAY             1051
#define IDC_CHKUSEGRAD                  1052
#define IDC_GENERATENEBPARAMS           1053
#define IDC_CHKANIMATE                  1053
#define IDC_CHKLOOP                     1054
#define IDC_LBLKEYFRAMES                1055
#define IDC_KEYFRAMES                   1056
#define IDC_LBLFRAMESPERKEY             1057
#define IDC_FRAMESPERKEY                1058

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
